### ISSUE TITLE
Doesn't seem to install

### ISSUE THREAD

**Issue by MadMartian** [TheWeirdDev/somafm-radio-gnome-ext#1]
Just get a generic ERROR banner from Gnome shell.  I've not written any Gnome extensions before but I am an experienced dev.  Let me know how I can help.

**Comment by TheWeirdDev** [comment]
Actually i found the problem yesterday while testing it on an 'Ubuntu Gnome 16.04' VM.
The main problem is  'stream-changed' event in [extension.js:169](https://github.com/alireza6677/somafm-radio-gnome-ext/blob/master/SomaFm-Radio%40alireza6677.gmail.com/extension.js#L169) that only works with gnome 3.20+. So i need an alternative solution to get the music title(description tag) and set the loading state to `false`. 
And I found one! (while writing this comment !!!).
I Think i fixed the code with a new listener that supports gnome 3.18 and before that: [radio.js:180](https://github.com/alireza6677/somafm-radio-gnome-ext/blob/master/SomaFm-Radio%40alireza6677.gmail.com/radio.js#L180) - [extension.js:161](https://github.com/alireza6677/somafm-radio-gnome-ext/blob/master/SomaFm-Radio%40alireza6677.gmail.com/extension.js#L161)

I need somebody to test it and tell me whether it's working or not.
Thank you. 👍

**Comment by MadMartian** [comment]
Works beautifully!  You nailed it!
