### ISSUE TITLE
Issue with version 3.32 ev. 24 on Ubuntu 19.04

### ISSUE THREAD

**Issue by GonzoDark** [TheWeirdDev/somafm-radio-gnome-ext#14]
Version 3.32 ev. 24 is not working on Ubuntu 19.04 (GNOME Shell 3.32.2).

The solution I have found is to downgrade to 3.32 ev. 22.

**I did the following steps in order to fix the issue:**

1. Disabled the plugin on the [extensions page ](https://extensions.gnome.org/extension/1237/somafm-internet-radio/)
2. Downloaded version 3.32 (ev. 22) from the [extensions page ](https://extensions.gnome.org/extension/1237/somafm-internet-radio/)
3. Extracted the file
4. Copied the files to my local gnome-shell extensions dir with the following command:

> cp -r 'SomaFm-Radioalireza6677.gmail.com.v22.shell-extension' ~/.local/share/gnome-shell/extensions/SomaFm-Radio@alireza6677.gmail.com
5. alt+F2, type r and hit enter

**Comment by TheWeirdDev** [comment]
Sorry i forgot to drop support for 3.32 and older versions of gnome-shell in metadata.json.

The latest version and the ones after that will only support the latest version of gnome-shell and changes are only made to provide compatibility for new gnome-shell versions.
No new feature is going to be added.

If you are using 3.32.x, stick to v22.
