### ISSUE TITLE
Install fails on gnome-shell-3.32.2-2.fc30.x86_64

### ISSUE THREAD

**Issue by bostrt** [TheWeirdDev/somafm-radio-gnome-ext#16]
Trying to reinstall plugin on Fedora 30 (Gnome 3.32.2-2) and receiving the following error:

```
Feb 21 11:49:16 xxxxxxxx gnome-shell[2468]: Extension "SomaFm-Radio@alireza6677.gmail.com" had error: TypeError: GObject.registerClass() used with invalid base class (is PopupBaseMenuItem)
```

**Comment by bostrt** [comment]
Possibly related: https://gitlab.gnome.org/GNOME/gnome-shell/issues/1069

**Comment by TheWeirdDev** [comment]
This is already discussed: https://github.com/TheWeirdDev/somafm-radio-gnome-ext/issues/14#issuecomment-534580212

Install version 22 from the gnome extensions website. newer versions will only support newer gnome-shell versions.
