### ISSUE TITLE
incompatible to gnome-shell 3.36

### ISSUE THREAD

**Issue by Gictorbit** [TheWeirdDev/somafm-radio-gnome-ext#17]
hi, thanks for your cool extension
seems your extension is not compatible with `version 3.36` of gnome-shell. recently I updated my gnome to version 3.36 and I couldn't use it anymore so I think it could be great that you release an update with gnome-shell new version support

**Comment by TheWeirdDev** [comment]
😂😂
Should be fixed now :)
