### ISSUE TITLE
Does not work under Ubuntu 20.04

### ISSUE THREAD

**Issue by dr-br** [TheWeirdDev/somafm-radio-gnome-ext#18]
**What:**
Extension can't be installed on my Ubuntu 20.04. Not via copying the corresponding folder to ~/.local/share/gnome-shell/extensions/ nor by using the gnome-shell extension manager in Firefox.

**Error-Log:** 

When trying to install via gnome-shell extension manager, `journalctl -f /usr/bin/gnome-shell` gives:
```
Jun 24 11:34:41 desktop gnome-shell[2660]: JS ERROR: Extension SomaFm-Radio@alireza6677.gmail.com: TypeError: item is undefined
                                           getChannel@/home/samuel/.local/share/gnome-shell/extensions/SomaFm-Radio@alireza6677.gmail.com/channels.js:127:5
                                           getLastChannel@/home/samuel/.local/share/gnome-shell/extensions/SomaFm-Radio@alireza6677.gmail.com/data.js:34:21
                                           enable@/home/samuel/.local/share/gnome-shell/extensions/SomaFm-Radio@alireza6677.gmail.com/extension.js:330:41
                                           _callExtensionEnable@resource:///org/gnome/shell/ui/extensionSystem.js:167:32
                                           loadExtension@resource:///org/gnome/shell/ui/extensionSystem.js:349:26
                                           callback@resource:///org/gnome/shell/ui/extensionDownloader.js:232:39
                                           gotExtensionZipFile/<@resource:///org/gnome/shell/ui/extensionDownloader.js:115:13
```

**System:**
uname -ra
Linux desktop 5.4.0-38-generic #42-Ubuntu SMP Mon Jun 8 14:14:24 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04 LTS
Release:	20.04
Codename:	focal

echo $XDG_SESSION_TYPE
wayland

**Comment by TheWeirdDev** [comment]
Remove `.somafm-radio/` in your home directory and restart gnome-shell

**Comment by dr-br** [comment]
Perfect. Works.
THANKS!!!
