### ISSUE TITLE
New channel and seasonal holiday channels

### ISSUE THREAD

**Issue by relayer370** [TheWeirdDev/somafm-radio-gnome-ext#23]
Request the addition of the new n5MD Radio channel, plus the holiday channels which are now live.  I checked out the latest git revision to have the extension work with Fedora 33, and modified the channels.js and downloaded the images.  

```
{ name: "n5MD Radio",               link: "http://ice3.somafm.com/n5md-64-aac",               pic: "/images/n5md-400.png",          num:33},
{ name: "SomaFM Specials",          link: "http://ice3.somafm.com/specials-64-aac",           pic: "/images/deptstorexmas120.jpg",  num:34},
{ name: "Christmas Lounge",         link: "http://ice3.somafm.com/christmas-64-aac",          pic: "/images/xmaslounge120.png",     num:35},
{ name: "Christmas Rocks!",         link: "http://ice3.somafm.com/xmasrocks-64-aac",          pic: "/images/xmasrocks120.png",      num:36},
{ name: "Xmas in Frisko",           link: "http://ice3.somafm.com/xmasinfrisko-64-aac",       pic: "/images/xmasinfrisco120.jpg",   num:37},
{ name: "Jolly Ol' Soul",           link: "http://ice3.somafm.com/jollysoul-64-aac",          pic: "/images/jollysoul120.png",      num:38},

```

**Comment by malck0** [comment]
A new request for 2023 ;) , best regards @TheWeirdDev

**Comment by TheWeirdDev** [comment]
> A new request for 2023 ;) , best regards @TheWeirdDev

Are the channels and links the same?

**Comment by malck0** [comment]
yes, it seems so, you can add too : 

name: "Department Store Christmas (Special)",               link: "http://ice3.somafm.com/deptstore-64-aac",               pic: "https://api.somafm.com/img/deptstore120.jpg"

**Comment by TheWeirdDev** [comment]
Thanks.
The new version is out (waiting for review) and it should automatically add holiday channels in December each year. Hopefully the links don't break.

**Comment by relayer370** [comment]
Cool, thanks for the update!

I found out today that the channels are listed on the somafm website in XML
and json format.  Maybe a full update to the extension isn't needed if it
could import them to be current without waiting for a release.

https://somafm.com/channels.xml
https://somafm.com/channels.json

**Comment by TheWeirdDev** [comment]
@relayer370 Nice, I wish I knew that before making it static.
Using the online list is not without any problems though. Network errors on startup could cause the extension to fail, user favorites need conversion and the order of channels might vary if they make changes.

For now, I stick with the existing idea but I think eventually it needs a rewrite.
