### ISSUE TITLE
Minor bug with bottom panel

### ISSUE THREAD

**Issue by Survolog** [TheWeirdDev/somafm-radio-gnome-ext#31]
To repeat this bug, it is required:

1. Place the system panel at the bottom. For example, by enabling the dash-to-panel extension.
2. Have enough radio stations to have more than the height of the screen.
3. Restart the somafm-radio-gnome-ext extension.

Expected behavior: when you click on the list of radio stations, a list of radio stations is displayed.

But my list is empty, although you can switch radio stations and add them to Favorites.

Thanks for the cool extension. It makes life more joyful.

**Comment by TheWeirdDev** [comment]
Hi, this sounds like a **dash-to-panel** bug. I can only guarantee this extension works in regular gnome environment. Maybe you should make an issue on their GitHub page?

I tried other extensions with long menus/sub-menus and they also have this issue with dash-to-panel, so it's not just my extension.

**Comment by Survolog** [comment]
Hmm. Then I'll close the bug. Sorry.

**Comment by TheWeirdDev** [comment]
No problem :heart:

**Comment by Survolog** [comment]
I did not look for a problem in the dash-to-panel code. I did this in extension.js file:
```
+import * as Util from 'resource:///org/gnome/shell/misc/util.js';
...
 export default class SomaFMRadioExtension extends Extension {
     enable() {
+        Util.spawnCommandLine("/bin/bash -c \"if gsettings --schemadir $HOME/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/schemas get org.gnome.shell.extensions.dash-to-panel panel-positions |grep -q BOTTOM; then gsettings --schemadir $HOME/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/schemas set org.gnome.shell.extensions.dash-to-panel panel-positions \'{\\\"0\\\":\\\"TOP\\\"}\'; gsettings --schemadir $HOME/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/schemas set org.gnome.shell.extensions.dash-to-panel panel-positions \'{\\\"0\\\":\\\"BOTTOM\\\"}\'; fi\"");
```
When launching the extension, if there is a dash-to-panel at the bottom, I put it top and put it down.
It's not need including in main code, but it solved my problem.
Maybe it will help someone else.
