### ISSUE TITLE
No playback on Bluetooth devices

### ISSUE THREAD

**Issue by DasJott** [TheWeirdDev/somafm-radio-gnome-ext#36]
I am not a 100% sure that this is a problem with this extension, but here is what happens:

I connected my headphones via bluetooth, but SomaFM-Extension plays back on internal speakers.
"Helvum" shows, that SomaFm pops up and is connected to internal speakers. I can only wire them additionally to the bluetooth device, but that sounds weird.

Shouldn't SomaFM-Extension not use the default output, set up in settings?

Using Fedora 41 with according Gnome with all the latest updates.

**Comment by TheWeirdDev** [comment]
The extension uses `gstreamer` for playing audio and that is responsible for selecting the output device. I expect it to choose the right output.

I tried my Bluetooth headset and it worked without an issue. Do you have any other extensions that might mess with audio settings? Or maybe some configurations you did a while ago and forgot?

This is what Helvum shows for me:
![image](https://github.com/user-attachments/assets/e3c9dc86-2f97-4f83-94cd-54a3de7b51e5)

And I've selected the Bluetooth device as my default output:
![image](https://github.com/user-attachments/assets/13430148-f167-4ff3-9c14-a8c0c1e25e80)

**Comment by TheWeirdDev** [comment]
This can be closed if there are no additional comments.

**Comment by DasJott** [comment]
Sorry, yes. I think the problem is not this wonderful extension. 
Thank you nonetheless for your reply and effort!

**Comment by DasJott** [comment]
Maybe interesting for others with similar problems, if Google may lead them here:

I connected my headphones using Bluetooth. 
Output was automatically switched to them ("Headset").
Sound from SomaFM still came from Speakers.
Switched Output to "Handsfree" - worked but of course bad quality.
Then switched to "Headset" again - works.

Still works on every connect since then. Kind of an unlock 😆
