### ISSUE TITLE
Always getting "--- Error ---"

### ISSUE THREAD

**Issue by bostrt** [TheWeirdDev/somafm-radio-gnome-ext#4]
I'm no longer able to stream music with the plugin and keep getting `--- Error ---`. Do you have any hints on where I should look for a cause of the error?

**Comment by TheWeirdDev** [comment]
Try to uninstall and then install the plugin. if that didn't work, install gstreamer plugins and codecs for your distro.

**Comment by TheWeirdDev** [comment]
And also please mention your distro and shell version.

**Comment by TheWeirdDev** [comment]
Tell me if this command plays radio or not. 
`gst-launch-1.0  playbin uri=http://ice2.somafm.com/lush-32-aac`

if it didn't, send me the output logs.

**Comment by bostrt** [comment]
@alireza6677 thanks for the reply, turns out it was a codec problem as you suggested. Am setting up a new laptop and missed that part :)

**Comment by mithunkalan** [comment]
this thread helped me. running 3.38 and always with the error. 
https://itsfoss.com/install-media-codecs-ubuntu/
