### ISSUE TITLE
Feature Request: Media button support

### ISSUE THREAD

**Issue by bostrt** [TheWeirdDev/somafm-radio-gnome-ext#5]
Would be great if the play/pause/previous/next keyboard media buttons integrated with somafm gnome ext

**Comment by TheWeirdDev** [comment]
That's actually a good idea. I will add it soon in the next week ✌️

**Comment by TheWeirdDev** [comment]
It may take longer than i thought 🤔🤔
I can't find any useful documentation and all the source codes on the internet are deprecated.

**Comment by captainju** [comment]
Isn't it the api we're looking for?
https://devdocs.baznga.org/keybinder30~3.0_api/

**Comment by TheWeirdDev** [comment]
> Isn't it the api we're looking for?
> https://devdocs.baznga.org/keybinder30~3.0_api/

I don't thinks so. It's not accessible in gjs.
