### ISSUE TITLE
The Silent Channel and Earwaves have been dropped

### ISSUE THREAD

**Issue by bostrt** [TheWeirdDev/somafm-radio-gnome-ext#6]
Looks like SomaFM dropped The Silent Channel and Earwaves. Can they be removed from this app?

> We hope you have enjoyed our broadcasts of Earwaves and The Silent Channel, both of which will conclude their broadcasts on December 30th, 2017. Thanks for listening. 17-Dec-2017

http://somafm.com/news/

**Comment by TheWeirdDev** [comment]
Done.
