### ISSUE TITLE
--- Error ---

### ISSUE THREAD

**Issue by btbroot** [TheWeirdDev/somafm-radio-gnome-ext#7]
Installed from extensions.gnome.org. For any channel, after swirling "Loading", quickly shows "--- Error ---".

What data to provide?

**Comment by TheWeirdDev** [comment]
SomaFM has changed the streaming URLs. run this command to update them:

`sed -i 's/ice2/ice3/' ~/.local/share/gnome-shell/extensions/SomaFm-Radio@alireza6677.gmail.com/channels.js`

then restart your gnome-shell using `Alt+F2` and `r` command.

or you can clone the repo with new changes and follow the [instructions](https://github.com/alireza6677/somafm-radio-gnome-ext/blob/master/Readme.md) to install the extension.

**Comment by btbroot** [comment]
Thanks for your suggestion! 

Does it mean, that you basically abandon this extension?

**Comment by TheWeirdDev** [comment]
I'll try my best to support the extension and fix issues like this one, but i probably won't update it on the gnome extensions website and i won't add any new features (unless the number of demands goes high).

**Comment by btbroot** [comment]
Now I realised that it's fixed in the code already.

Could you elaborate why you don't plan to update extensions.gnome.org anymore? That would be a pity

**Comment by TheWeirdDev** [comment]
They take a lot of time to review and accept the update, it's kind of a bummer.

Honestly i thought this extension would have more users than it already has, the links where broken for a while and nobody but you noticed. 

Anyway, i can send the update to the website if you like, that's no problem. ✌️
